server:
  servlet:
    context-path: /sell
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.128:3306/sell?serverTimezone=UTC&characterEncoding=utf-8
  jpa:
    show-sql: true
  freemarker:
    suffix: .ftl
#   连接redis
#  redis:
#    host: 192.168.1.128
#    port: 6379